--In Management Studio, enable Query --> SQLCMD Mode


:setvar ECMdbname "P11ECM"


if not exists (select * from $(ECMdbname).[dbo].sysobjects where name='TransactionsTest' and xtype='U')
	CREATE TABLE [dbo].[TransactionsTest](
		[Id] [int] NOT NULL,
		[TradeDate] [datetime] NOT NULL,
		[TradeTime] [datetime] NOT NULL,
		[NotedTime] [datetime] NOT NULL,
		[UserId] [varchar](255) NOT NULL,
		[Amount] [float] NOT NULL,
		[Price] [float] NOT NULL,
		[ReferringId] [int] NOT NULL,
		[TransTypeId] [int] NOT NULL,
		[InstrumentId] [int] NOT NULL,
		[PortfolioId] [int] NOT NULL,
		[StatusId] [int] NOT NULL,
		[ClearingTypeId] [int] NOT NULL,
		[OrderId] [int] NOT NULL,
		[AuthId] [int] NULL,
		[ExchangeId] [int] NOT NULL,
		[BFeeCurrencyId] [int] NULL,
		[CFeeCurrencyId] [int] NULL,
		[CurrencyId] [int] NULL,
		[CurrencyMargin] [float] NULL,
		[PriceBasisId] [int] NULL,
		[TicketNumber] [varchar](50) NULL,
		[Comment] [varchar](1000) NULL,
		[CurrencySourceId] [int] NOT NULL,
		[DeliveryTypeId] [int] NOT NULL,
		[TimeZoneOffset] [int] NOT NULL,
		[TU_Id] [int] NOT NULL,
		[TUP_Id] [int] NOT NULL,
		[PriceUnitId] [int] NOT NULL,
		[OrgVolumeUnitId] [int] NOT NULL,
		[OrgPriceUnitId] [int] NOT NULL,
		[T_BDA_Id] [int] NULL,
		[OrgAmount] [float] NULL,
		[OrgPrice] [float] NULL,
		[ExternalId] [varchar](255) NULL,
		[ExternalSourceName] [varchar](255) NULL,
		[ContractForm] [varchar](30) NULL,
		[ExchangeRate] [float] NULL,
		[ExchangedFrom] [int] NULL,
		[VT_ID] [smallint] NULL,
		[FromCountryId] [varchar](5) NULL,
		[DistrParentId] [int] NULL,
		[DistrAmount] [float] NULL,
		[Markup] [float] NULL,
		[ConfirmedByBroker] [bit] NOT NULL,
		[ConfirmedByCounterparty] [bit] NOT NULL,
		[Payout] [float] NULL,
		[LowerTrigger] [float] NULL,
		[UpperTrigger] [float] NULL,
		[ExpiryTime] [datetime] NULL,
		[MarketPriceMultiplicator] [float] NULL,
		[SettlementRuleId] [int] NULL,
		[InterconnectorId] [int] NULL,
		[Interruptible] [bit] NULL,
		[UserSpecifiedName] [varchar](255) NULL,
		[BalanceAreaId] [int] NULL,
		[TriggerCurrencyId] [int] NULL,
		[SchedulingAccountTypeId] [int] NULL,
		[SchedulingNominationProcedureId] [int] NULL,
		[ToCountryId] [varchar](5) NULL,
		[EnvironmentLabelId] [int] NULL,
		[ReplicationId] [uniqueidentifier] NOT NULL,
		[IndexedPriceBookTemplateId] [int] NULL,
		[SwapPriceTypeId] [int] NULL,
		[MasterAgreementId] [int] NULL,
		[CashSettlementPeriodContainerId] [int] NULL,
		[SamplingFrom] [datetime] NULL,
		[SamplingTo] [datetime] NULL,
		[RiskValue] [float] NULL,
		[GroupField1] [varchar](255) NOT NULL,
		[GroupField2] [varchar](255) NOT NULL,
		[GroupField3] [varchar](255) NOT NULL,
		[CustomCompanyId] [varchar](255) NOT NULL,
		[CustomCompanyName] [varchar](255) NOT NULL,
		[UnderlyingInstrumentID] [int] NULL,
		[UnderlyingDeliveryTypeId] [int] NULL,
		[TimeZoneId] [nvarchar](255) NULL,
		[UTI] [varchar](53) NULL,
		[TimeStampClearedUTC] [datetime] NULL,
		[TimeStampConfirmationBrokerUTC] [datetime] NULL,
		[TimeStampConfirmationCounterpartyUTC] [datetime] NULL,
		[DealCompression] [int] NULL,
		[TerminationDate] [date] NULL,
		[PricebasisToAreaId] [int] NULL,
		[EMIRStatus] [varchar](20) NULL,
		[FlexibleTimeSeries] [bit] NOT NULL,
		[ContractType] [varchar](20) NULL,
		[CapacityId] [varchar](50) NULL,
		[ModelTypeId] [int] NULL,
		[LocationId] [int] NULL,
		[InitiatorAggressorId] [int] NULL,
		[RemitReporting] [bit] NOT NULL,
		[CertificateLimitFactor] [float] NULL,
		[CtCparty] [bit] NULL,
		[Originator] [bit] NULL,
		[AuthConfirmed] [bit] NULL,
		[OTCBroker] [int] NULL,
		[TradeCompanyId] [int] NULL,
		[DeclareId] [int] NULL,
		[LoadProfileId] [int] NULL,
		[GridPointId] [int] NULL,
		[TraderId] [int] NULL,
		[MinVol] [float] NULL,
		[MaxVol] [float] NULL,
		[FixPrice] [float] NULL,
		[Threshold] [float] NULL,
		[Paid] [bit] NULL,
		[DeclaredVolume] [float] NULL,
		[ContractSplitId] [int] NULL,
		[InitialPrice] [float] NULL,
		[CapacityBidVolume] [float] NULL,
		[CapacityBidPrice] [float] NULL,
		[AuctionType] [varchar](50) NULL,
		[LastUpdatedUTC] [datetime2](7) NOT NULL,
		[CapacityTradeVolume] [float] NULL,
		[AuctionTypeId] [int] NULL,
		[HistoricContractPriceSeriesId] [int] NULL,
		[HistoricMarketPriceSeriesId] [int] NULL,
		[CounterpartyTrader] [varchar](100) NULL,
		[ReferencePriceSeriesId] [int] NULL,
		[DestinationReferencePriceSeriesId] [int] NULL
		)
ELSE
	TRUNCATE TABLE $(ECMdbname).[dbo].[TransactionsTest]


if NOT exists (select * from $(ECMdbname).[dbo].sysobjects where name='InstrumentCertificatesTest' and xtype='U')
	CREATE TABLE $(ECMdbname).[dbo].[InstrumentCertificatesTest](
		[InstrumentId] [int] NOT NULL,
		[ProductionFacilityId] [int] NULL,
		[CertificateTypeId] [int] NOT NULL,
		[DateOfTransfer] [datetime] NOT NULL
	)
ELSE
	TRUNCATE TABLE $(ECMdbname).[dbo].[InstrumentCertificatesTest]

if NOT exists (select * from $(ECMdbname).[dbo].sysobjects where name='InstrumentsTest' and xtype='U')
	CREATE TABLE $(ECMdbname).[dbo].[InstrumentsTest](
		[InstrumentId] [int] NOT NULL,
		[InstrumentName] [varchar](50) NULL,
		[InstrumentShortName] [varchar](15) NULL,
		[InstrumentTypeId] [int] NOT NULL,
		[StatusId] [int] NOT NULL,
		[ExecutionVenueId] [int] NULL,
		[CommodityId] [int] NULL,
		[ExpiryOffset] [int] NULL,
		[StripPeriodResolution] [varchar](1) NULL,
		[BarrierOptionTypeId] [int] NULL,
		[FromDate] [datetime] NULL,
		[ToDate] [datetime] NULL,
		[ExpiryDate] [datetime] NULL,
		[Strike] [float] NULL,
		[SamplingPeriodId] [int] NULL,
		[PutCall] [bit] NULL,
		[Hours] [int] NULL,
		[BaseCurrencyId] [int] NULL,
		[CrossCurrencyId] [int] NULL,
		[BookPriceTypeId] [int] NULL,
		[CapFloorPricingPeriodTypeId] [int] NULL,
		[FutureTypeId] [int] NULL,
		[DeliveryTypeId] [int] NULL,
		[ExpiryTime] [datetime] NULL,
		[LoadProfileId] [int] NULL,
		[PriceBasisId] [int] NULL,
		[SamplingFrom] [datetime] NULL,
		[SamplingTo] [datetime] NULL,
		[SwapPriceTypeId] [int] NULL,
		[TimeZoneId] [nvarchar](255) NULL,
		[UnderlyingInstrumentId] [int] NULL,
		[CurrencyId] [int] NULL,
		[CurrencySourceId] [int] NULL,
		[TU_Id] [int] NULL,
		[PriceUnitId] [int] NULL,
		[Payout] [float] NULL,
		[LowerTrigger] [float] NULL,
		[UpperTrigger] [float] NULL,
		[TriggerCurrencyId] [int] NULL,
		[MarketPriceFactor] [float] NULL,
		[SettlementRuleId] [int] NULL,
		[InterconnectorId] [int] NULL,
		[Interruptible] [bit] NULL,
		[UserSpecifiedName] [varchar](255) NULL,
		[EnvironmentLabelId] [int] NULL,
		[IndexedPriceBookTemplateId] [int] NULL,
		[PriceBasisToAreaId] [int] NULL,
		[ModelTypeId] [int] NULL,
		[MinVol] [float] NULL,
		[MaxVol] [float] NULL,
		[FixPrice] [float] NULL,
		[Threshold] [float] NULL,
		[HistoricContractPriceSeriesId] [int] NULL,
		[HistoricMarketPriceSeriesId] [int] NULL,
		[ReferencePriceSeriesId] [int] NULL,
		[DestinationReferencePriceSeriesId] [int] NULL,
		[PublishingPeriodTypeId] [int] NULL
		)
ELSE
	TRUNCATE TABLE $(ECMdbname).[dbo].InstrumentsTest




INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (1, 'AAA', '', 3, 1, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (2, 'AAA', '', 3, 1, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (3, 'BBB', '', 3, 1, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (4, 'AAA', 'B', 3, 1, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (5, 'AAA', '', 4, 1, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (6, 'AAA', '', 3, 2, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (7, 'AAA', '', 3, 1, 2, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (8, 'AAA', '', 3, 1, 1, 2, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (9, 'AAA', '', 3, 1, 1, 1, NULL, NULL, NULL, '2020-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (10, 'AAA', '', 3, 1, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2022-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (11, 'AAA', '', 3, 1, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2209, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (12, 'AAA', '', 3, 1, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (13, 'AAA', '', 3, 1, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10)
INSERT INTO $(ECMdbname).dbo.InstrumentsTest ([InstrumentId], [InstrumentName], [InstrumentShortName], [InstrumentTypeId], [StatusId], [ExecutionVenueId], [CommodityId], [ExpiryOffset], [StripPeriodResolution], [BarrierOptionTypeId], [FromDate], [ToDate], [ExpiryDate], [Strike], [SamplingPeriodId], [PutCall], [Hours], [BaseCurrencyId], [CrossCurrencyId], [BookPriceTypeId], [CapFloorPricingPeriodTypeId], [FutureTypeId], [DeliveryTypeId], [ExpiryTime], [LoadProfileId], [PriceBasisId], [SamplingFrom], [SamplingTo], [SwapPriceTypeId], [TimeZoneId], [UnderlyingInstrumentId], [CurrencyId], [CurrencySourceId], [TU_Id], [PriceUnitId], [Payout], [LowerTrigger], [UpperTrigger], [TriggerCurrencyId], [MarketPriceFactor], [SettlementRuleId], [InterconnectorId], [Interruptible], [UserSpecifiedName], [EnvironmentLabelId], [IndexedPriceBookTemplateId], [PriceBasisToAreaId], [ModelTypeId], [MinVol], [MaxVol], [FixPrice], [Threshold], [HistoricContractPriceSeriesId], [HistoricMarketPriceSeriesId], [ReferencePriceSeriesId], [DestinationReferencePriceSeriesId], [PublishingPeriodTypeId]) VALUES (14, 'AAA', '', 3, 1, 1, 1, NULL, NULL, NULL, '2021-07-01 00:00:00.000', '2021-09-30 00:00:00.000', NULL, NULL, NULL, NULL, 2208, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15)


INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (1, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,1,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (2, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,2,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (3, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,3,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (4, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,4,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (5, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,5,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (6, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,6,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (7, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,7,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (8, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,8,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (9, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,9,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (10, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,10,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (11, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,11,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (12, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,12,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (13, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,13,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (14, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,14,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL, NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (15, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,1,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 1,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (16, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,2,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 2,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (17, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,3,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 3,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (18, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,4,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 4,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (19, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,5,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 5,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (20, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,6,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 6,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (21, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,7,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 7,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (22, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,8,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 8,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (23, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,9,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 9,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (24, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,10,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 10,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (25, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,11,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 11,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (26, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,12,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 12,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (27, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,13,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 13,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (28, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,14,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', 14,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO $(ECMdbname).dbo.TransactionsTest (Id,TradeDate,TradeTime,NotedTime,UserId,Amount,Price,ReferringId,TransTypeId,InstrumentId,PortfolioId,StatusId,ClearingTypeId,OrderId,AuthId,ExchangeId,BFeeCurrencyId,CFeeCurrencyId,CurrencyId,CurrencyMargin,PriceBasisId,TicketNumber,Comment,CurrencySourceId,DeliveryTypeId,TimeZoneOffset,TU_Id,TUP_Id,PriceUnitId,OrgVolumeUnitId,OrgPriceUnitId,T_BDA_Id,OrgAmount,OrgPrice,ExternalId,ExternalSourceName,ContractForm,ExchangeRate,ExchangedFrom,VT_ID,FromCountryId,DistrParentId,DistrAmount,Markup,ConfirmedByBroker,ConfirmedByCounterparty,Payout,LowerTrigger,UpperTrigger,ExpiryTime,MarketPriceMultiplicator,SettlementRuleId,InterconnectorId,Interruptible,UserSpecifiedName,BalanceAreaId,TriggerCurrencyId,SchedulingAccountTypeId,SchedulingNominationProcedureId,ToCountryId,EnvironmentLabelId,ReplicationId,IndexedPriceBookTemplateId,SwapPriceTypeId,MasterAgreementId,CashSettlementPeriodContainerId,SamplingFrom,SamplingTo,RiskValue,GroupField1,GroupField2,GroupField3,CustomCompanyId,CustomCompanyName,UnderlyingInstrumentID,UnderlyingDeliveryTypeId,TimeZoneId,UTI,TimeStampClearedUTC,TimeStampConfirmationBrokerUTC,TimeStampConfirmationCounterpartyUTC,DealCompression,TerminationDate,PricebasisToAreaId,EMIRStatus,FlexibleTimeSeries,ContractType,CapacityId,ModelTypeId,LocationId,InitiatorAggressorId,RemitReporting,CertificateLimitFactor,CtCparty,Originator,AuthConfirmed,OTCBroker,TradeCompanyId,DeclareId,LoadProfileId,GridPointId,TraderId,MinVol,MaxVol,FixPrice,Threshold,Paid,DeclaredVolume,ContractSplitId,InitialPrice,CapacityBidVolume,CapacityBidPrice,AuctionType,LastUpdatedUTC,CapacityTradeVolume,AuctionTypeId,HistoricContractPriceSeriesId,HistoricMarketPriceSeriesId,CounterpartyTrader,ReferencePriceSeriesId,DestinationReferencePriceSeriesId) VALUES (29, '2019-01-03 00:00:00.000', '2019-01-03 12:51:40.000', '2019-02-20 11:51:42.000', 'Vizard', 0,0,10933,2,1,23,1,1,1,0,0,NULL,NULL,4,NULL,NULL,NULL,NULL,3,2,0,1,1,1,1,1,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL, '81A6BDDD-8CF9-4393-B2FB-A109AE8205BC', NULL,NULL,NULL,NULL,NULL,NULL,0, '', '', '', '', '', NULL,NULL, 'Central Europe Standard Time', NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, '2019-02-20 11:51:43.0792582', NULL,NULL,NULL,NULL,NULL,NULL,NULL)
